version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: shop-db
    environment:
      POSTGRES_USER: shopper
      POSTGRES_PASSWORD: sAfe_Pass5ord
      POSTGRES_DB: shop-db
    ports:
      - "5430:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
