CREATE SEQUENCE carts_sequence
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1;

CREATE TABLE carts
(
    id         BIGINT PRIMARY KEY,
    user_id    BIGINT UNIQUE REFERENCES users (id),
    created_at TIMESTAMP DEFAULT NOW()
);