# -----------------------------------------------------------
# SERVER / PORT
# -----------------------------------------------------------
quarkus.http.port=${PORT:8080}
quarkus.http.host=0.0.0.0
# -----------------------------------------------------------
# CORS
# -----------------------------------------------------------
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,PATCH,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
quarkus.http.cors.exposed-headers=location,content-disposition
# -----------------------------------------------------------
# OPENID CONNECT / KEYCLOAK
# -----------------------------------------------------------
quarkus.oidc.auth-server-url=${KEYCLOAK_URL:http://localhost:8180/realms/shop}
quarkus.oidc.client-id=shop-api
quarkus.oidc.application-type=service
# optional für Rollen aus Keycloak
quarkus.oidc.roles.role-claim-path=realm_access/roles
# -----------------------------------------------------------
# AUTHORIZATION
# -----------------------------------------------------------
quarkus.http.auth.permission.public.paths=/product/*,/category/*
quarkus.http.auth.permission.public.policy=permit
quarkus.http.auth.permission.authenticated.paths=/users/me,/cart/*,/order/*
quarkus.http.auth.permission.authenticated.policy=authenticated
# -----------------------------------------------------------
# DATABASE
# -----------------------------------------------------------
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=${QUARKUS_DATASOURCE_JDBC_URL:jdbc:postgresql://localhost:5430/shop}
quarkus.datasource.username=${QUARKUS_DATASOURCE_USERNAME:shopper}
quarkus.datasource.password=${QUARKUS_DATASOURCE_PASSWORD:sAfe_Pass5ord}
quarkus.datasource.jdbc.max-size=8
quarkus.datasource.jdbc.min-size=2
# -----------------------------------------------------------
# FLYWAY
# -----------------------------------------------------------
quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=true
quarkus.flyway.locations=db/migration,db/testdata
# -----------------------------------------------------------
# HIBERNATE / BLAZE PERSISTENCE
# -----------------------------------------------------------
quarkus.hibernate-orm.scripts.generation=none
blaze.persistence.entity-view.configuration.classes=com.example.view.*
# -----------------------------------------------------------
# LOGGING
# -----------------------------------------------------------
quarkus.log.level=INFO
quarkus.log.console.level=INFO
quarkus.log.category."io.quarkus.oidc".level=DEBUG